#!/usr/bin/env python3
"""
Pit & Masa — Logo & Icon Kit packager
========================================
Assembles all Pit & Masa brand logo and icon assets from the site into a
neatly-organised ZIP archive ready for download.

Output: pit-masa/public/resources/downloads/pit-masa-logo-kit.zip

Folder structure inside the ZIP:
  Pit-Masa-Logo-Kit/
    README.txt
    Primary-Logo/
      pit-masa-logo-white.png        (586 x 626 — full-resolution primary logo)
    Circle-Mark/
      pit-masa-logo-circle.png       (928 x 928 — standalone icon / avatar mark)
    Favicons/
      favicon.ico                    (multi-size ICO, generated by Next.js)
      favicon-192x192.png            (PWA / Android home-screen icon)
      favicon-512x512.png            (PWA splash / large icon)
      apple-touch-icon-180x180.png   (iOS home-screen icon)
    Social/
      og-image-1200x630.jpg          (Open Graph / social share image)
"""

import os
import shutil
import zipfile
import textwrap
from datetime import date

# ── Paths ─────────────────────────────────────────────────────────────
SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT   = os.path.join(SCRIPT_DIR, "..")
PUBLIC      = os.path.join(REPO_ROOT, "pit-masa", "public")
SRC_APP     = os.path.join(REPO_ROOT, "pit-masa", "src", "app")
OUTPUT_DIR  = os.path.join(PUBLIC, "resources", "downloads")
ZIP_NAME    = "pit-masa-logo-kit.zip"
ZIP_PATH    = os.path.join(OUTPUT_DIR, ZIP_NAME)
ZIP_ROOT    = "Pit-Masa-Logo-Kit"      # top-level folder inside the ZIP

# ── Asset manifest ─────────────────────────────────────────────
# (zip_path_inside_archive, source_file_path)
ASSETS = [
    # Primary logo
    (f"{ZIP_ROOT}/Primary-Logo/pit-masa-logo-white.png",
     os.path.join(PUBLIC, "images", "pit-masa-logo-white.png")),

    # Circle mark
    (f"{ZIP_ROOT}/Circle-Mark/pit-masa-logo-circle.png",
     os.path.join(PUBLIC, "images", "pit-masa-logo-circle.png")),

    # Favicons
    (f"{ZIP_ROOT}/Favicons/favicon.ico",
     os.path.join(SRC_APP, "favicon.ico")),
    (f"{ZIP_ROOT}/Favicons/favicon-192x192.png",
     os.path.join(PUBLIC, "icon.png")),
    (f"{ZIP_ROOT}/Favicons/favicon-512x512.png",
     os.path.join(PUBLIC, "icon-512.png")),
    (f"{ZIP_ROOT}/Favicons/apple-touch-icon-180x180.png",
     os.path.join(PUBLIC, "apple-icon.png")),

    # Social
    (f"{ZIP_ROOT}/Social/og-image-1200x630.jpg",
     os.path.join(PUBLIC, "og-image.jpg")),
]

# ── README content ────────────────────────────────────────────────────
README = textwrap.dedent(f"""\
    PIT & MASA — Logo & Icon Kit
    ================================
    Version 1.0  |  {date.today().strftime("%B %Y")}
    pitandmasa.com  |  events@pitandmasa.com  |  (860) 321-8646
    55 Main Street, Hartford, CT 06103

    ── CONTENTS ───────────────────────────────────────────────────────

    Primary-Logo/
      pit-masa-logo-white.png
        Full-resolution primary logo (586 x 626 px, transparent PNG).
        White wordmark + icon on transparent background.
        Use on: Dark (#080808), green (#0f3d15), or any dark/photo background.
        Minimum size: 80 px wide (digital)  |  30 mm wide (print)

    Circle-Mark/
      pit-masa-logo-circle.png
        Standalone icon / avatar mark (928 x 928 px, transparent PNG).
        Use for: profile pictures, favicons (custom builds), app icons,
        social media avatars, watermarks, and tight-space applications.
        Minimum size: 24 px wide (digital)  |  8 mm wide (print)

    Favicons/
      favicon.ico                    Multi-size ICO (16, 32, 48 px) for browsers
      favicon-192x192.png            PWA / Android home-screen icon
      favicon-512x512.png            PWA splash screen / large app icon
      apple-touch-icon-180x180.png   iOS Safari home-screen icon (180 x 180 px)

    Social/
      og-image-1200x630.jpg
        Open Graph / social share image used when pitandmasa.com links are shared
        on Facebook, LinkedIn, iMessage, Slack, etc.
        Dimensions: 1200 x 630 px (standard OG ratio 1.91:1)

    ── BRAND COLORS ───────────────────────────────────────────────────

      Background   #080808   RGB(8, 8, 8)         Primary dark canvas
      Brand Green  #65B207   RGB(101, 178, 7)     Accent, CTAs, highlights
      Section Grn  #0f3d15   RGB(15, 61, 21)      Section backgrounds
      Foreground   #ffffff   RGB(255, 255, 255)   Headings on dark
      Card BG      #131E13   RGB(19, 30, 19)      Card / panel background
      Muted FG     #a0a0a0   RGB(160, 160, 160)   Supporting text

    ── TYPOGRAPHY ─────────────────────────────────────────────────────

      Headings  Red Hat Display  Weight 900 (Black)
      Body      Red Hat Text     Weight 400 (Regular)
      Both fonts are available free via Google Fonts:
      https://fonts.google.com/specimen/Red+Hat+Display
      https://fonts.google.com/specimen/Red+Hat+Text

    ── USAGE RULES ────────────────────────────────────────────────────

      APPROVED logo backgrounds:
        • #080808  (primary dark)
        • #0f3d15  (section green)
        • #131E13  (card / muted)
        • #1a2a1a  (card variant)
        • Photography with sufficient dark overlay

      NEVER:
        • Stretch, skew, or rotate the logo
        • Recolor outside of approved palette
        • Place on low-contrast backgrounds without an overlay
        • Add drop shadows, outlines, or effects
        • Use below minimum size thresholds

    ── CONTACT ────────────────────────────────────────────────────────

      Website    pitandmasa.com
      Email      events@pitandmasa.com
      Phone      (860) 321-8646
      Instagram  @pitandmasa
      Facebook   facebook.com/pitandmasa
      LinkedIn   linkedin.com/company/pitandmasa
      YouTube    youtube.com/@pitandmasa
      TikTok     tiktok.com/@pitandmasa

    © {date.today().year} Pit & Masa LLC. All rights reserved.
    This logo kit is for use by Pit & Masa and authorized partners only.
""")


def build_zip():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    missing = [src for _, src in ASSETS if not os.path.exists(src)]
    if missing:
        print("WARNING — missing files (will be skipped):")
        for m in missing:
            print(f"  {m}")

    with zipfile.ZipFile(ZIP_PATH, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        # README
        zf.writestr(f"{ZIP_ROOT}/README.txt", README)

        # Assets
        for arc_path, src_path in ASSETS:
            if os.path.exists(src_path):
                zf.write(src_path, arc_path)
                size_kb = os.path.getsize(src_path) / 1024
                print(f"  + {arc_path}  ({size_kb:.0f} KB)")
            else:
                print(f"  - SKIPPED (not found): {arc_path}")

    zip_size = os.path.getsize(ZIP_PATH) / 1024
    print(f"\nLogo kit ZIP created: {ZIP_PATH}")
    print(f"Archive size: {zip_size:.0f} KB")

    # Print contents summary
    print("\nArchive contents:")
    with zipfile.ZipFile(ZIP_PATH, "r") as zf:
        for info in zf.infolist():
            print(f"  {info.filename}  ({info.file_size / 1024:.0f} KB)")


if __name__ == "__main__":
    build_zip()
